Repository FOB-7avaScript/wanted-moducompany-project, pull requests merged in 2021-08, with the labels that each got.

#1 Docs: Update README.md
  README.md
Labels: docs

#2 Feat : Header, Main 레이아웃 구성
  .eslintrc
  package-lock.json
  package.json
  src/App.tsx
  src/Components/AppLayout.tsx
  src/Components/Header.tsx
  src/Components/index.tsx
  src/Pages/index.tsx
  src/Styles/Reset.tsx
  src/Styles/index.tsx
Labels: feature

#8 Feat: Todo item 삭제 logic 구현
  package-lock.json
  src/App.tsx
  src/Pages/Delete/Delete.tsx
  src/Utils/GetDataFromLocalStorage.tsx
  src/Utils/SaveDataToLocalStorage.tsx
Labels: feature

#9 Feat : #3 Header UI 구현
  package-lock.json
  package.json
  src/Components/Header.tsx
Labels: style

#11 Feat : #5 DateRangePicker 구현
  package-lock.json
  package.json
  src/Components/DatePicker.tsx
Labels: feature

#18 Feature/drag n drop
  src/Components/DragNDrop.tsx
  src/Pages/Delete/Delete.tsx
  src/Pages/List/TodoContainer.tsx
  src/Pages/List/TodoList.tsx
  src/store/drag.tsx
Labels: feature

#44 Feat: Style cursor pointer
  src/Pages/List/TodoItem.tsx
Labels: feature
